### PR TITLE
Fix slower API calls in customer cards display

### LINKED ISSUE #145: Loading module slow
Hello,

The loading of module in ajax checkout slows the page of several seconds. I've found that the problem in function of class \Stripe\Account::retrieve(). Commenting, infact, from hookPaymentOptions the checkApiConnection (that uses retrieve) and also the var stripeAccount the loading of scripts are much faster (about 20ms against 1200ms).

I would to know if it depends from stripe's server latency or not and if its possible to increases the speed.

Thank you

### PR DESCRIPTION
**Pull request by Afayadas**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Requests to Stripe are slower in the Payment hook.
| Type?         | improvement 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes #145 (35213)

### CODE REVIEW

File: classes/StripeCustomer.php [hunk 1]
```diff
@@ -107,19 +107,28 @@ public function getCustomerById($id_customer, $id_account)
...
+                $stripe_customer_id
+            );
 
-        foreach ($customersList as $customer) {
-            if ($customer['id'] == $stripe_customer_id) {
-                return true;
-            }
+            return $email === $customer->email;
+        } catch (Exception $e) {
+            error_log($e->getMessage());
```
Comment (clotairer) [inline classes/StripeCustomer.php:117]: ProcessLogger instead ?

File: stripe_official.php [hunk 2]
```diff
@@ -1739,7 +1738,9 @@ public function hookPayment($params)
             return;
         }
 
-        if (!$this->checkApiConnection()) {
+        $stripeAccount = $this->checkApiConnection();
+
+        if ($stripeAccount === false) {
```
Comment (clotairer) [inline stripe_official.php:1743]: strict condition probably too strict or with empty($stripeAccount) === true

**Review by clotairer — CHANGES_REQUESTED** [review]
